---
- name: checks if the archived package is installed
  ansible.builtin.stat:
    path: "/Applications/{{ item.name }}.app"
  register: archived_package

- name: overwrites archived packages
  block:
  - name: downloads the archived package
    ansible.builtin.get_url:
      url: "{{ item.url }}"
      dest: "{{ macos_download_path }}/{{ item.name }}"

  - name: installs the archived package
    ansible.builtin.unarchive:
      src: "{{ macos_download_path }}/{{ item.name }}"
      dest: /Applications
      remote_src: yes

  - name: deletes the installation package
    ansible.builtin.file:
      path: "{{ macos_download_path }}/{{ item.name }}"
      state: absent
  when: macos_overwrite or not archived_package.stat.exists
