- name: checks if AdoptOpenJDK is installed
  ansible.builtin.stat:
    path: "/Library/Java/JavaVirtualMachines/{{ item.name }}.jdk"
  register: java

- name: installs Java
  block:
  - name: downloads AdoptOpenJDK
    ansible.builtin.get_url:
      url: "{{ item.url }}"
      dest: "{{ macos_download_path }}"
      checksum: "{{ item.checksum }}"

  - name: installs AdoptOpenJDK
    become: yes
    ansible.builtin.command: "installer -pkg {{ macos_download_path }}/{{ item.package }} -target /"
    args:
      creates: "/Library/Java/JavaVirtualMachines/{{ item.name }}"

  - name: deletes AdoptOpenJDK installation package
    ansible.builtin.file:
      path: "{{ macos_download_path }}/{{ item.package }}"
      state: absent
  when: macos_overwrite or not java.stat.exists
