---
- include_tasks: preflight.yml

- name: applies macOS customizations
  ansible.builtin.include_role:
    name: ayltai.macos_preferences

- name: installs applications with App Store
  ansible.builtin.include_role:
    name: ayltai.macos_appstore

- include_tasks: homebrew.yml

- name: installs Visual Studio Code and extensions
  ansible.builtin.include_role:
    name: ayltai.vscode_mac
  when: macos_vscode

- include_tasks: archived-packages.yml
  loop: "{{ macos_archived_packages }}"

- include_tasks: open-source-packages.yml
- include_tasks: preferences.yml
