---
- name: installs Hack fonts
  block:
  - name: checks if Hack fonts are installed
    ansible.builtin.stat:
      path: "{{ ansible_env.HOME }}/Library/Fonts/Hack-Regular.ttf"
    register: hack_fonts

  - name: overwrites Hack fonts
    block:
    - name: downloads Hack fonts
      ansible.builtin.get_url:
        url: "{{ macos_hack_fonts_url }}"
        dest: "{{ macos_download_path }}"

    - name: decompresses Hack fonts
      ansible.builtin.unarchive:
        src: "{{ macos_download_path }}/{{ macos_hack_fonts_package }}"
        dest: "{{ macos_download_path }}"

    - name: installs Hack fonts
      ansible.builtin.copy:
        src: "{{ macos_download_path }}/ttf/{{ item }}"
        dest: "{{ ansible_env.HOME }}/Library/Fonts/{{ item }}"
        remote_src: yes
      with_items:
        - Hack-Bold.ttf
        - Hack-BoldItalic.ttf
        - Hack-Italic.ttf
        - Hack-Regular.ttf

    - name: deletes Hack fonts installation packages
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
        remote_src: yes
      with_items:
        - "{{ macos_download_path }}/{{ macos_hack_fonts_package }}"
        - "{{ macos_download_path }}/ttf"
    when: macos_overwrite or not hack_fonts.stat.exists
  when: macos_hack_fonts

- name: installs Resizer
  block:
  - name: checks if Resizer is installed
    ansible.builtin.stat:
      path: "{{ ansible_env.HOME }}/Library/Services/Resize.workflow"
    register: resizer

  - name: overwrites Resizer
    block:
    - name: git clones Resizer
      ansible.builtin.git:
        repo: https://github.com/ayltai/Resizer.git
        dest: "{{ macos_download_path }}/Resizer"
        version: master

    - name: installs Resizer
      ansible.builtin.command: ./install.command
      args:
        chdir: "{{ macos_download_path }}/Resizer"
        creates: "{{ ansible_env.HOME }}/Library/Services/Resize.workflow"

    - name: deletes Resizer installation package
      ansible.builtin.file:
        path: "{{ macos_download_path }}/Resizer"
        state: absent
    when: macos_overwrite or not resizer.stat.exists
  when: macos_resizer
