---
- name: sets email address for Git
  git_config:
    name: user.email
    value: "{{ git_user_email }}"
  when: git_user_email is defined

- name: sets user name for Git
  git_config:
    name: user.name
    value: "{{ git_user_name }}"
  when: git_user_name is defined

- name: adds environment variables to Bash profile
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.bash_profile"
    block: |
      alias ll='ls -la'

      # Colors
      C_DEFAULT="\[\033[m\]"
      C_WHITE="\[\033[1m\]"
      C_BLACK="\[\033[30m\]"
      C_RED="\[\033[31m\]"
      C_GREEN="\[\033[32m\]"
      C_YELLOW="\[\033[33m\]"
      C_BLUE="\[\033[34m\]"
      C_PURPLE="\[\033[35m\]"
      C_CYAN="\[\033[36m\]"
      C_LIGHTGRAY="\[\033[37m\]"
      C_DARKGRAY="\[\033[1;30m\]"
      C_LIGHTRED="\[\033[1;31m\]"
      C_LIGHTGREEN="\[\033[1;32m\]"
      C_LIGHTYELLOW="\[\033[1;33m\]"
      C_LIGHTBLUE="\[\033[1;34m\]"
      C_LIGHTPURPLE="\[\033[1;35m\]"
      C_LIGHTCYAN="\[\033[1;36m\]"
      C_BG_BLACK="\[\033[40m\]"
      C_BG_RED="\[\033[41m\]"
      C_BG_GREEN="\[\033[42m\]"
      C_BG_YELLOW="\[\033[43m\]"
      C_BG_BLUE="\[\033[44m\]"
      C_BG_PURPLE="\[\033[45m\]"
      C_BG_CYAN="\[\033[46m\]"
      C_BG_LIGHTGRAY="\[\033[47m\]"

      export CLICOLOR=1
      export LSCOLORS=GxFxCxDxBxegedabagaced

      parse_git_branch() {
          git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
      }

      export PS1="\n$C_LIGHTGRAY\D{%F %T} $C_LIGHTGREEN\u$C_LIGHTGRAY@$C_LIGHTCYAN\h $C_LIGHTGRAY: $C_LIGHTYELLOW\w $C_LIGHTRED\$(parse_git_branch)\[\e[00m\]\n$C_LIGHTGRAY\$$C_DEFAULT"
    create: yes
